# Generated by Django 4.1.1 on 2022-09-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_carousel_product_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
