# Generated by Django 4.1.1 on 2022-11-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
